site_name: Finnize-Docs
site_url: https://example.com

nav:
    - Introduction: intro.md
    - Quickstart: quick_start.md
    - Datasets: datasets.md
    - Market Data: market_data.md
    - Generate Signals: generate_signals.md
    - Technical Indicator: technical_indicator.md
    - Util Function: util_function.md
    - Strategy Builder: strategy_builder.md
    - Backtest: backtest.md
    - Live Trading: live_trading.md
    - Python Support: python_support.md
    - Keep Test:
          - Test Getting Started: Test_Getting Started.md
          - Test Visual Programming: Test_Visual Programming.md
          - Test Live Trading: Test_Live Trading.md
          - Test Strategy Building: Test_Strategy Building.md
          - Test Placing Order: Test_Placing Order.md
    - Test: Test.md

theme:
    name: material
    features:
        - content.code.annotate
        - content.tabs.link

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
