name: Publish Ezyquant Document

on:
  push:
    tags:
      - 'v*.*.*'
      
jobs:
  build-n-publish:
    name: Build and publish Python Document
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Upgrade pip
      run: |
          pip install --upgrade pip
    - name: requirements install
      run: |
          pip install -U -r requirements-dev.txt
    - name: Sphinx Build
      run: |
          sphinx-build -b html docs/source/ docs/build/html
    - name: Check HTML
      run: |
          cd docs/build/html
          pwd
          ls
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: Deploy Document
      run: aws s3 sync ./docs/build/html s3://doc.ezyquant.com --delete