name: Publish PYPI

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build-n-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          make install

      - name: Build a binary wheel and a source tarball
        run: |
          hatch build

      - name: Publish distribution
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
